# Generated by Django 3.1.5 on 2021-02-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user_quantity',
            new_name='quantity',
        ),
    ]
