# Generated by Django 3.1.5 on 2021-02-10 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_wishitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='wishitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
