# Generated by Django 3.1.5 on 2021-02-03 09:58

from django.db import migrations
import photo.fields
import shopwindow.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopwindow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=photo.fields.ThumbnailImageField(blank=True, upload_to=shopwindow.models.user_directory_path, verbose_name='IMAGE'),
        ),
    ]
