# Generated by Django 3.1.5 on 2021-02-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopwindow', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
