# Generated by Django 3.1.5 on 2021-02-09 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopwindow', '0003_auto_20210209_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopwindow.product'),
        ),
    ]
