# Generated by Django 3.1.5 on 2021-02-09 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopwindow', '0005_auto_20210209_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='product',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopwindow.question'),
        ),
    ]
