# Generated by Django 3.1.5 on 2021-02-10 09:48

from django.db import migrations
import photo.fields
import shopwindow.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopwindow', '0006_auto_20210209_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=photo.fields.ThumbnailImageField(blank=True, null=True, upload_to=shopwindow.models.user_directory_path, verbose_name='IMAGE'),
        ),
    ]
