# Generated by Django 3.1.5 on 2021-02-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210205_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
