# Generated by Django 3.1.5 on 2021-02-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210205_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-order_date',)},
        ),
        migrations.AddField(
            model_name='order',
            name='modify_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE'),
        ),
    ]
