# Generated by Django 3.1.5 on 2021-02-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210206_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Order_set',
            new_name='order_set',
        ),
    ]
