# Generated by Django 3.1.5 on 2021-02-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210206_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_set',
            field=models.IntegerField(default=-1),
        ),
    ]
